import type { Period } from "@/shared/lib/period"

const MONTHS_PER_YEAR = 12

const toMonthIndex = ({ year, month }: Period): number =>
  year * MONTHS_PER_YEAR + (month - 1)

export const isPeriodOnOrAfter = (period: Period, reference: Period): boolean =>
  toMonthIndex(period) >= toMonthIndex(reference)

/** One generated month of a recurring plan, as the page table shows it. */
export type RecurringRow = {
  occurrenceId: string
  planId: string
  concept: string
  groupLabel: string
  currency: string
  amount: number | null
  amountIsEstimated: boolean
  /** An explicit absence: neither an expense nor a missing amount. */
  isSkipped: boolean
  defaultAmount: number | null
  totalInstallments: number | null
  stoppedFrom: Period | null
}

export type RecurringPlanOccurrence = {
  year: number
  month: number
  amount: number | null
  isSkipped: boolean
}

/** A recurring plan with every month it already generated. */
export type RecurringPlan = {
  planId: string
  concept: string
  groupLabel: string
  currency: string
  defaultAmount: number | null
  totalInstallments: number | null
  stoppedFrom: Period | null
  occurrences: readonly RecurringPlanOccurrence[]
}

/** A plan that can still generate the viewed month, and how to prefill it. */
export type PendingRecurringPlan = {
  planId: string
  concept: string
  groupLabel: string
  currency: string
  defaultAmount: number | null
  /**
   * The last amount really loaded for this plan, used to estimate a variable
   * one. Null when nothing was ever loaded, so there is nothing to estimate
   * from and the field starts empty.
   */
  lastKnownAmount: number | null
}

export const isStoppedAt = (
  stoppedFrom: Period | null,
  period: Period
): boolean => stoppedFrom !== null && isPeriodOnOrAfter(period, stoppedFrom)

const lastKnownAmountOf = (plan: RecurringPlan): number | null => {
  const knownOccurrences = plan.occurrences
    .filter((occurrence) => !occurrence.isSkipped && occurrence.amount !== null)
    .sort(
      (left, right) =>
        toMonthIndex({ year: left.year, month: left.month }) -
        toMonthIndex({ year: right.year, month: right.month })
    )

  return knownOccurrences.at(-1)?.amount ?? null
}

/**
 * RF-05 / AGENTS.md: nothing is generated by reading a month, so this only
 * answers which plans the explicit generation would offer. A plan is left out
 * when it is stopped for that month, when the month is already generated (even
 * if it was skipped), or when it already used up its number of months.
 */
export const toPendingRecurringPlans = (
  plans: readonly RecurringPlan[],
  period: Period
): PendingRecurringPlan[] =>
  plans
    .filter((plan) => {
      if (isStoppedAt(plan.stoppedFrom, period)) {
        return false
      }

      const isAlreadyGenerated = plan.occurrences.some(
        (occurrence) =>
          occurrence.year === period.year && occurrence.month === period.month
      )

      if (isAlreadyGenerated) {
        return false
      }

      return (
        plan.totalInstallments === null ||
        plan.occurrences.length < plan.totalInstallments
      )
    })
    .map((plan) => ({
      planId: plan.planId,
      concept: plan.concept,
      groupLabel: plan.groupLabel,
      currency: plan.currency,
      defaultAmount: plan.defaultAmount,
      lastKnownAmount: lastKnownAmountOf(plan),
    }))
