import { useQuery } from "@tanstack/react-query"

import type { Period } from "@/shared/lib/period"
import { supabase } from "@/shared/lib/supabase/client"

import type { RecurringPlan, RecurringRow } from "../model/recurring-plans"

export const RECURRING_KIND = "recurring"

// Query keys carry the owner and the month so two sessions or two months never
// share a cache entry.
export const recurringKeys = {
  byUser: (userId: string) => ["recurring-expenses", userId] as const,
  month: (userId: string, { year, month }: Period) =>
    ["recurring-expenses", userId, "month", year, month] as const,
  plans: (userId: string) => ["recurring-expenses", userId, "plans"] as const,
}

const toStoppedFrom = (
  year: number | null,
  month: number | null
): Period | null => (year === null || month === null ? null : { year, month })

export const fetchRecurringOccurrences = async ({
  year,
  month,
}: Period): Promise<RecurringRow[]> => {
  // RLS scopes the read to the authenticated user, so no user_id filter here.
  // The "!inner" join is what makes the kind filter drop the occurrences of
  // other plan kinds instead of only emptying the embedded plan.
  const { data, error } = await supabase
    .from("expense_occurrences")
    .select(
      "id, plan_id, amount, amount_is_estimated, is_skipped, spending_plans!inner(id, concept, group_label, currency, default_amount, total_installments, stopped_from_year, stopped_from_month)"
    )
    .eq("year", year)
    .eq("month", month)
    .eq("spending_plans.kind", RECURRING_KIND)

  if (error) {
    throw new Error(error.message)
  }

  return (data ?? []).map((row) => ({
    occurrenceId: row.id,
    planId: row.spending_plans.id,
    concept: row.spending_plans.concept,
    groupLabel: row.spending_plans.group_label,
    currency: row.spending_plans.currency,
    amount: row.amount,
    amountIsEstimated: row.amount_is_estimated,
    isSkipped: row.is_skipped,
    defaultAmount: row.spending_plans.default_amount,
    totalInstallments: row.spending_plans.total_installments,
    stoppedFrom: toStoppedFrom(
      row.spending_plans.stopped_from_year,
      row.spending_plans.stopped_from_month
    ),
  }))
}

/**
 * Every recurring plan with the months it already generated. Which of them are
 * still pending for the viewed month is decided by toPendingRecurringPlans, a
 * pure read: nothing is ever generated by looking at a month.
 */
export const fetchRecurringPlans = async (): Promise<RecurringPlan[]> => {
  const { data, error } = await supabase
    .from("spending_plans")
    .select(
      "id, concept, group_label, currency, default_amount, total_installments, stopped_from_year, stopped_from_month, expense_occurrences(year, month, amount, is_skipped)"
    )
    .eq("kind", RECURRING_KIND)

  if (error) {
    throw new Error(error.message)
  }

  return (data ?? []).map((plan) => ({
    planId: plan.id,
    concept: plan.concept,
    groupLabel: plan.group_label,
    currency: plan.currency,
    defaultAmount: plan.default_amount,
    totalInstallments: plan.total_installments,
    stoppedFrom: toStoppedFrom(plan.stopped_from_year, plan.stopped_from_month),
    occurrences: (plan.expense_occurrences ?? []).map((occurrence) => ({
      year: occurrence.year,
      month: occurrence.month,
      amount: occurrence.amount,
      isSkipped: occurrence.is_skipped,
    })),
  }))
}

export const useRecurringOccurrencesQuery = (
  userId: string | null,
  period: Period
) =>
  useQuery({
    queryKey: recurringKeys.month(userId ?? "", period),
    queryFn: () => fetchRecurringOccurrences(period),
    enabled: userId !== null,
  })

export const useRecurringPlansQuery = (userId: string | null) =>
  useQuery({
    queryKey: recurringKeys.plans(userId ?? ""),
    queryFn: fetchRecurringPlans,
    enabled: userId !== null,
  })
