// AUTO-GENERATED by `pnpm supabase:types` -- do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      expense_occurrences: {
        Row: {
          amount: number | null
          amount_is_estimated: boolean
          created_at: string
          id: string
          installment_number: number | null
          is_skipped: boolean
          month: number
          plan_id: string
          updated_at: string
          user_id: string
          year: number
        }
        Insert: {
          amount?: number | null
          amount_is_estimated?: boolean
          created_at?: string
          id?: string
          installment_number?: number | null
          is_skipped?: boolean
          month: number
          plan_id: string
          updated_at?: string
          user_id: string
          year: number
        }
        Update: {
          amount?: number | null
          amount_is_estimated?: boolean
          created_at?: string
          id?: string
          installment_number?: number | null
          is_skipped?: boolean
          month?: number
          plan_id?: string
          updated_at?: string
          user_id?: string
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "expense_occurrences_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "spending_plans"
            referencedColumns: ["id"]
          },
        ]
      }
      monthly_budgets: {
        Row: {
          created_at: string
          exchange_rate_fetched_at: string | null
          exchange_rate_source: string | null
          exchange_rate_source_updated_at: string | null
          exchange_rate_value: number | null
          id: string
          month: number
          salary_ars: number | null
          updated_at: string
          user_id: string
          year: number
        }
        Insert: {
          created_at?: string
          exchange_rate_fetched_at?: string | null
          exchange_rate_source?: string | null
          exchange_rate_source_updated_at?: string | null
          exchange_rate_value?: number | null
          id?: string
          month: number
          salary_ars?: number | null
          updated_at?: string
          user_id: string
          year: number
        }
        Update: {
          created_at?: string
          exchange_rate_fetched_at?: string | null
          exchange_rate_source?: string | null
          exchange_rate_source_updated_at?: string | null
          exchange_rate_value?: number | null
          id?: string
          month?: number
          salary_ars?: number | null
          updated_at?: string
          user_id?: string
          year?: number
        }
        Relationships: []
      }
      other_expenses: {
        Row: {
          amount: number
          concept: string
          created_at: string
          currency: string
          id: string
          month: number
          payment_method: string | null
          updated_at: string
          user_id: string
          year: number
        }
        Insert: {
          amount: number
          concept: string
          created_at?: string
          currency: string
          id?: string
          month: number
          payment_method?: string | null
          updated_at?: string
          user_id: string
          year: number
        }
        Update: {
          amount?: number
          concept?: string
          created_at?: string
          currency?: string
          id?: string
          month?: number
          payment_method?: string | null
          updated_at?: string
          user_id?: string
          year?: number
        }
        Relationships: []
      }
      spending_plans: {
        Row: {
          concept: string
          created_at: string
          currency: string
          default_amount: number | null
          group_label: string
          id: string
          kind: string
          stopped_from_month: number | null
          stopped_from_year: number | null
          total_installments: number | null
          updated_at: string
          user_id: string
        }
        Insert: {
          concept: string
          created_at?: string
          currency: string
          default_amount?: number | null
          group_label: string
          id?: string
          kind: string
          stopped_from_month?: number | null
          stopped_from_year?: number | null
          total_installments?: number | null
          updated_at?: string
          user_id: string
        }
        Update: {
          concept?: string
          created_at?: string
          currency?: string
          default_amount?: number | null
          group_label?: string
          id?: string
          kind?: string
          stopped_from_month?: number | null
          stopped_from_year?: number | null
          total_installments?: number | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      create_card_purchase: {
        Args: {
          p_card: string
          p_concept: string
          p_currency: string
          p_month: number
          p_quota_amount: number
          p_starting_installment: number
          p_total_installments: number
          p_year: number
        }
        Returns: string
      }
      create_card_purchases_batch: {
        Args: {
          p_card: string
          p_items: Json
          p_month: number
          p_year: number
        }
        Returns: undefined
      }
      create_loan: {
        Args: {
          p_concept: string
          p_entity: string
          p_month: number
          p_quota_amount: number
          p_starting_installment: number
          p_total_installments: number
          p_year: number
        }
        Returns: string
      }
      create_recurring_plan: {
        Args: {
          p_concept: string
          p_currency: string
          p_default_amount?: number
          p_group_label: string
          p_month: number
          p_starting_amount: number
          p_total_installments?: number
          p_year: number
        }
        Returns: string
      }
      set_loan_installment_amounts: {
        Args: { p_items: Json }
        Returns: undefined
      }
      set_recurring_occurrence_amount: {
        Args: {
          p_amount: number
          p_is_estimated: boolean
          p_occurrence_id: string
        }
        Returns: undefined
      }
      set_recurring_occurrences: {
        Args: { p_items: Json; p_month: number; p_year: number }
        Returns: undefined
      }
      stop_recurring_plan: {
        Args: { p_from_month: number; p_from_year: number; p_plan_id: string }
        Returns: undefined
      }
      update_card_purchase: {
        Args: {
          p_card: string
          p_concept: string
          p_currency: string
          p_from_installment: number
          p_from_month: number
          p_from_year: number
          p_plan_id: string
          p_quota_amount: number
          p_total_installments: number
        }
        Returns: undefined
      }
      update_loan: {
        Args: {
          p_concept: string
          p_entity: string
          p_from_installment: number
          p_from_month: number
          p_from_year: number
          p_plan_id: string
          p_total_installments: number
        }
        Returns: undefined
      }
      update_recurring_plan: {
        Args: {
          p_concept: string
          p_currency: string
          p_default_amount?: number
          p_from_month: number
          p_from_year: number
          p_group_label: string
          p_plan_id: string
          p_total_installments?: number
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
